name: Run detekt
description: Detekt

inputs:
  github-token:
    description: GitHub Token
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: "17"
        distribution: "temurin"
    - name: Cache gradle
      uses: gradle/gradle-build-action@v2
    - name: Validate gradle wrapper
      uses: gradle/wrapper-validation-action@v1
    - name: Run detekt
      shell: bash
      run: ./gradlew detekt
    - name: Setup reviewdog
      if: always()
      uses: reviewdog/action-setup@v1
    - name: Run reviewdog
      if: always()
      shell: bash
      run: cat build/reports/detekt/merge.xml | reviewdog -level=warning -f=checkstyle -name=detekt -reporter=github-check
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ inputs.github-token }}
    - name: Upload results to GitHub repository
      if: always()
      uses: github/codeql-action/upload-sarif@v2
      with:
        ref:
        sarif_file: build/reports/detekt/merge.sarif
        checkout_path: ${{ github.workspace }}
