name: Build
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize

jobs:
  detekt:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/detekt

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/build
