name: Build
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize

jobs:
  detekt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: vaniland-mc/actions/detekt@v1
        with:
          report-xml-path: build/reports/detekt/merge.xml
          report-sarif-path: build/reports/detekt/merge.sarif

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build
