name: detekt
on:
  workflow_call: { }

jobs:
  detekt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
      - name: Cache gradle
        uses: gradle/gradle-build-action@v2
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Run detekt
        run: ./gradlew detekt
      - name: Setup reviewdog
        if: always()
        uses: reviewdog/action-setup@v1
      - name: Run reviewdog
        if: always()
        run: cat build/reports/detekt/merge.xml | reviewdog -level=warning -f=checkstyle -name=detekt -reporter=github-check
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload results to GitHub repository
        if: always()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: build/reports/detekt/merge.sarif
          checkout_path: ${{ github.workspace }}
