name: Check PR has release/* label

on:
  pull_request:
    types:
      - opened
      - reopened
      - labeled
      - unlabeled
      - synchronize
    branches:
      - main

jobs:
  require-release-label:
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        id: release-label
        with:
          one_of: release/major,release/minor,release/patch,release/none
          repo_token: ${{ secrets.GITHUB_TOKEN }}
