name: Test Report
on:
  workflow_run:
    workflows: [ 'Publish Release' ]
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v1
        with:
          artifact: test-results            # artifact name
          name: Kotest                      # Name of the check run which will be created
          path: 'TEST-*.xml'                # Path to test results (inside artifact .zip)
          reporter: java-junit              # Format of test results
